[versions]

# Minecraft
minecraft = "1.21.9"
fabric-api = "0.134.0"
neoforge = "21.9.0-beta"

# Libraries
rlib = "3.9.0"

# Plugins
resourceful-loom = "1.0.6"

[libraries]

rlib-common = { module = "com.teamresourceful.resourcefullib:resourcefullib-common-1.21.9", version.ref = "rlib" }
rlib-fabric = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.9", version.ref = "rlib" }
rlib-neoforge = { module = "com.teamresourceful.resourcefullib:resourcefullib-neoforge-1.21.9", version.ref = "rlib" }

[plugins]

resourceful-loom = { id = "com.teamresourceful.plugins.loom", version.ref = "resourceful-loom" }
resourceful-gradle = { id = "com.teamresourceful.resourcefulgradle" }