[versions]

# Minecraft
minecraft = "1.21.6"
fabric-api = "0.128.2"
neoforge = "21.6.20-beta"

# Libraries
rlib = "3.6.0"

# Plugins
resourceful-loom = "1.0.5"

[libraries]

rlib-common = { module = "com.teamresourceful.resourcefullib:resourcefullib-common-1.21.6", version.ref = "rlib" }
rlib-fabric = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.6", version.ref = "rlib" }
rlib-neoforge = { module = "com.teamresourceful.resourcefullib:resourcefullib-neoforge-1.21.6", version.ref = "rlib" }

[plugins]

resourceful-loom = { id = "com.teamresourceful.plugins.loom", version.ref = "resourceful-loom" }
resourceful-gradle = { id = "com.teamresourceful.resourcefulgradle" }